from pymongo import MongoClient
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import MongoDBAtlasVectorSearch
from langchain.document_loaders import DirectoryLoader
from langchain.llms import OpenAI 
from langchain.chains import RetrievalQA

import gradio as gr 
from gradio.themes.base import Base 
import key_param


client = MongoClient(key_param.MONGO_URI)
dbName = "langchain_demo"
collectionName = "collection_of_text_blobs"
collection = client[dbName][collectionName]

loader = DirectoryLoader("./sample_files", glob="./*.txt", show_progress=True)
data = loader.load()


embeddings = OpenAIEmbeddings(openai_api_key=key_param.OPENAI_API_KEY)

index_name_mongo = "vector_index"

vectorStore = MongoDBAtlasVectorSearch.from_documents(
    documents=data, 
    embedding=embeddings, 
    collection=collection,
    index_name=index_name_mongo
)


def query_data(query):
    docs = vectorStore.similarity_search(query, k=1) # retrieve the most relevant document 
    if not docs:
        return "No results from vector search empty", "No results from retriever."

    as_output = docs[0].page_content # the content with the most similar document from the atlas vector search

    llm = OpenAI(
        openai_api_key=key_param.OPENAI_API_KEY, 
        model_name="gpt-3.5-turbo-instruct",
        temperature=0) # lower temperature makes the model more deterministic and less creative 
    retriever = vectorStore.as_retriever() # for fetching documents relevant to our query 
    qa = RetrievalQA.from_chain_type(llm, chain_type="stuff", retriever=retriever) # stuff document chain takes a list documents, insert some onto a prompt and passes the prompts to an LLM 
    retriever_output = qa.run(query) # executes the chain 

    # source:  https://www.youtube.com/watch?v=JEBDfGqrAUA&t=2366s
    return as_output, retriever_output  



# create a web interface with gradio 
with gr.Blocks(theme=Base(), title="Question Answering App using Vector Search + RAG") as demo:
    gr.Markdown(
        """
        # Question Answering App using Atlas Vector Search + RAG Architecture 
        """
    )
    textbox = gr.Textbox(label="Enter your Question:")
    with gr.Row():
        button = gr.Button("Submit", variant="primary")
    with gr.Column(): 
        output1 = gr.Textbox(lines=1, max_lines=10, label="Output with just Atlas Vector Search (returns text field as is): ")
        output2 = gr.Textbox(lines=1, max_lines=10, label="Output generated by chaining Atlas Vector Search to Langchain's RetrieverQA + OpenAI LLM: ")
    
    button.click(query_data, textbox, outputs=[output1, output2])


demo.launch(share=True)



